In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math
# from google.colab import drive
# drive.mount('/content/gdrive')

In [ ]:
df=pd.read_csv("drive/My Drive/Colab Notebooks/Datasets/testingGradientDescent.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [ ]:
def gradientDescent(x,y):
  mCurr=bCurr=0
  iterations=100
  n=len(x)
  learningRate=0.0002
  costPrev=0
  
  for i in range(iterations):
    yPredict=mCurr*x+bCurr
    cost=(1/n)*sum([val**2 for val in (y-yPredict)])
    md=-(2/n)*sum(x*(y-yPredict))
    bd=-(2/n)*sum(y-yPredict)
    mCurr=mCurr-learningRate*md
    bCurr=bCurr-learningRate*bd
    # print("iterations: ",i," mCurr: ",mCurr," bCurr: ",bCurr," cost: ",cost)
    if(math.isclose(costPrev,cost,abs_tol=1e-20)):
      break
    costPrev=cost  


In [ ]:
x=np.array(df['math'])
y=np.array(df['cs'])
r=linear_model.LinearRegression()
r.fit(df[['math']],y)
gradientDescent(x,y)
print("coeffcient: ",r.coef_," intercept: ",r.intercept_)



coeffcient:  [1.01773624]  intercept:  1.9152193111569034


In [ ]:
import pickle

with open('drive/My Drive/Colab Notebooks/Datasets/modelPickle',"wb") as f:
  pickle.dump(r,f) 

with open('drive/My Drive/Colab Notebooks/Datasets/modelPickle',"rb") as f:
  newModel=pickle.load(f)  

r.predict([[5000]])  

array([5090.5964086])

In [ ]:
newModel.predict([[5000]])

array([5090.5964086])

In [ ]:
pip install joblib

In [ ]:
# from sklearn.externals import joblib

joblib.dump(r,'modelJoblib')

newModelJoblib=joblib.load('modelJoblib')
newModelJoblib.predict([[5000]])

array([5090.5964086])