<a href="https://colab.research.google.com/github/MST9/ML-Algorithm/blob/main/MultivariateLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


hoping I am able to upload data from local drive


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
#df=pd.read_csv("gdrive/My Drive/Colab Notebooks/LinearRegressionMultivariate.csv") ## Uploading from google drive by running mount google and copy pasting Oauth2
df=pd.read_csv("drive/My Drive/Colab Notebooks/LinearRegressionMultivariate.csv")  ##Uploading from google drive from Files in colab
#df=pd.read_csv("LinearRegressionMultivariate.csv")                                  ## Uploading in colab from local drive
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
medianBedroom=math.floor(df.bedrooms.mean())

medianBedroom

3

In [4]:
df.bedrooms=df.bedrooms.fillna(medianBedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

383724.99999999994

In [ ]:
reg.predict([[3000,3,15]])

array([615025.])

In [27]:
import math
# df1=pd.read_csv("gdrive/My Drive/Colab Notebooks/hiring.csv")
df1=pd.read_csv("drive/My Drive/Colab Notebooks/hiring.csv")

df1['test_score(out of 10)']=df1['test_score(out of 10)'].fillna(math.floor(df1['test_score(out of 10)'].mean()))
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [28]:
pip install word2number

In [32]:
from word2number import w2n #


df1.experience = df1.experience.fillna("zero")
df1.experience = df1.experience.apply(w2n.word_to_num)

df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [34]:
reg1=linear_model.LinearRegression()
reg1.fit(df1[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']],df1['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [36]:
reg1.predict([[12,10,10]])

array([93747.79628651])